### ISSUE TITLE
Won't install under Blender 3.4.1

### ISSUE THREAD

**Issue by noc2art** [nutti/OpenAI-Bridge#1]
I'm sorry but although I followed the installation instructions to the tee, Blender 3.4.1 won't see the addon! I even tried installing from the zip file to no avail.

**Comment by nutti** [comment]
@noc2art 

What add-on version do you use?

**Comment by noc2art** [comment]
Hi. I downloaded v0.2.0

**Comment by noc2art** [comment]
Oh wait, correction. The whole thing stemmed from the fact that I downloaded 0.1.0. Now I made sure that I downloaded 0.2.0 and it shows up in the prefs. Yet I get a warning that told me that this version was authored for 3.5 and might cause problems. Will the addon work ok under 3.4.1?

**Comment by noc2art** [comment]
And I'm getting this error consistently: ```
Sent Request: f{'model': 'gpt-3.5-turbo', 'messages': [{'role': 'user', 'content': 'create a cube'}]}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.openai.com:443
DEBUG:urllib3.connectionpool:https://api.openai.com:443 "POST /v1/chat/completions HTTP/1.1" 429 206
Terminated Message Processing Timer
```

**Comment by noc2art** [comment]
My API key is in place and I'm in my free trial period.

**Comment by nutti** [comment]
Thanks for your information.
But I could not find the solution from your log.

Could you try to turn off `Async Execution` and tell me the error?

![github_20230411](https://user-images.githubusercontent.com/1463952/231152667-cb33f813-cd93-413a-9f0a-78c9f1c9856b.png)

**Comment by noc2art** [comment]
So sorry for the late reply. Here's the error from the console after activating "Asynch Execution"

`Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\openai_bridge\op\chat.py", line 521, in execute
    sync_request(api_key, 'CHAT', request, options, context, self)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\openai_bridge\utils\threading.py", line 450, in sync_request
    RequestHandler.handle_request(request, sync=True, context=context, operator_instance=operator_instance)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\openai_bridge\utils\threading.py", line 420, in handle_request
    cls.handle_chat_request(api_key, transaction_id, req_data, options, sync=sync, context=context, operator_instance=operator_instance)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\openai_bridge\utils\threading.py", line 328, in handle_chat_request
    response.raise_for_status()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/chat/completions`

**Comment by nutti** [comment]
@noc2art 

Thanks.
Do you use this add-on behind the organization proxy?
Or does the below solution help for your issue?
https://stackoverflow.com/questions/75041580/openai-api-giving-error-429-too-many-requests

**Comment by nutti** [comment]
Close this issue because of no response for a long time.
