### ISSUE TITLE
openAIの支払いについて

### ISSUE THREAD

**Issue by tetsujikenny** [nutti/OpenAI-Bridge#2]
blenderにapikeyも入力したものの、openaiの支払いのことが書かれていないせいか反応しません

openapiはopenaiとは別に支払いが発生しますよね。解説では支払いが必要とあるのですが、それはopenaiだけの20ドルのことですか?そしてapiも使うので、使った単語数によって支払いが発生するという意味ですか?

**Comment by nutti** [comment]
@tetsujikenny 

報告ありがとうございます。APIの疎通機能も将来的に追加したいと考えています。

> それはopenaiだけの20ドルのことですか?

OpenAI APIの料金体系になります。
OpenAI Plus向けに20ドル支払うのとは別になります。
料金体系の詳しくは以下のページから確認できます。
https://openai.com/pricing

> そしてapiも使うので、使った単語数によって支払いが発生するという意味ですか?

その通りです。
OpenAI API（Language Modelの場合）はトークン数によって支払いが発生します。

**Comment by nutti** [comment]
@tetsujikenny 

こちら何かアップデートはありましたか？
もし問題なければIssueを閉じようと思います。

**Comment by nutti** [comment]
本Issueはいったんクローズします。
