### ISSUE TITLE
Unathorized for url

### ISSUE THREAD

**Issue by Blaxine** [nutti/OpenAI-Bridge#3]
### System Information
  
* OS: Windows
* Blender version: 3.0.0
* Add-on version: 0.2.0

### Description about the bug**

I downloaded this through the blender market website, the version 0.2.0  after installing the addon without doing any modifications to its default settings entering a prompt will cause a warning
:Error: 401 Client Error: Unauthorized for url: https://api.openai.com/v1/chat/completions

the addon appears to have an "API" key that i seem to not find on this download files on the blender market if it needs one 

if it requires an api key to generate something  please provide a text with the api key of the add on or an instruction file as to how it should be installed as well 

changing addon configurations between default, image or chat has no result and return the same output on the console of unauthorized url

### Screenshots/Files [Optional]  
![image](https://user-images.githubusercontent.com/50810426/233837518-16a952e7-4dc0-44b0-8777-e0e89dc7b069.png)
![image](https://user-images.githubusercontent.com/50810426/233837544-03b63e1d-78d9-41cc-b351-729f7cfbf848.png)

**Comment by nutti** [comment]
@Blaxine 

> the addon appears to have an "API" key that i seem to not find on this download files on the blender market if it needs one

At first, you need to get API key from OpenAI site as mentioned below.
https://github.com/nutti/OpenAI-Bridge/blob/main/docs/tutorial.md#preparation
The API key is not free, so you need to pay additional fee for using API.

**Comment by nutti** [comment]
Close this issue because of no response for a long time.
