### ISSUE TITLE
Why does it show an error and a link timeout even though I have filled in the secret key?

### ISSUE THREAD

**Issue by TJX1222341424** [nutti/OpenAI-Bridge#5]
### System Information
  
* OS: [e.g. Windows]
* Blender version: [e.g. 2.79]
* Add-on version: [e.g. 5.2]

### Expected behavior

*The behavior you expect about the feature you reported.*

### Description about the bug**

*The description about the bug.*

### Screenshots/Files [Optional]  

*It is good to solve the bug if you attach the screenshots or .blend file.*

**Comment by TJX1222341424** [comment]
![8701d96e27b3649e45189a6dddd5125](https://github.com/nutti/OpenAI-Bridge/assets/136305471/00d52ea0-2cca-40a3-af93-468b278d7968)

**Comment by TJX1222341424** [comment]
The secret key is correct, other software can use this key, I hope someone can help me to see

**Comment by nutti** [comment]
@TJX1222341424 

I think you requested a lot to OpenAI API.
Do you use this add-on behind the corporate proxy or send lots of requests?

**Comment by nutti** [comment]
@TJX1222341424 

Any update?

**Comment by nutti** [comment]
Close this issue for now.

@TJX1222341424 
Please ping us if this is available for you.
